"""empty message

Revision ID: d38a02559da2
Revises: 96f8d9b65812
Create Date: 2018-03-20 20:32:43.670952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd38a02559da2'
down_revision = '96f8d9b65812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('article', sa.Column('password', sa.String(length=50), nullable=False))
    op.add_column('article', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('article', 'content')
    op.drop_column('article', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('article', sa.Column('content', mysql.TEXT(), nullable=False))
    op.drop_column('article', 'username')
    op.drop_column('article', 'password')
    op.drop_column('article', 'email')
    # ### end Alembic commands ###
